language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: de3f2499ba5f61c0c5d455b21a368eeb57eb98de
 local_dir: dist
 on:
   branch: master