language: node_js
node_js:
- node
cache: npm
script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 api_key:
    secure: e5F6dAmiOzO8eunwq/vIA9I4WvMIjsihgQJzVKnvMwuy+F99JBSKLrZHRSv6EqkjKACy1hjs1r3APmKi+v+70IJvyJVTDASR20YPYv2te4A3YqV2gGBIewoh60uu/PW75dDiuTJo/HHYe0SPuE2qlp3/RDYU6UM7uhlE9vqearzH2d3IkYd7gyxbnIjMOZDbuR50sgtxqhzGMLG9sM454XckxMJCqcr0zu+LmDQoX3IeeHztHTda/4sGBkFOe5LFtc7sqdfvgW85EcZYAcTbElzFh38hPen5V6auo7ogB+g00AQMH72QjMlDW5tvCyogff2OesYSsF0KnwM8gZEeA/zwFeIU0OdFA+3HQJAhryYy9637HLpl0bgnR3GhnqWP1HzNplM/BOcK+x6ZP7OU+WJ34xiCu4/xBQoYtkRwP60JTp5A3qS3knRpUNVGCO9T8bSb5sAt6b2dyrLiOzdadE6ETWtPbUSInfBydIPwykkHcLof/zx20BqffPQs4aCliBYHRS84HY3Sv4tr+eeex9lIb3Xq030nxQVlwlK3l3XeZWEWrIg6QunGIXhS3czgqwyFTmdKvslOUL04yMxJWah0fk0w1Aywfi7UviQ2cal0Wm9OgJ83XRyds5Lf1bjXWtE85bOU+nFGTQwYCupWSA52emLnF7pTaoJDCKdPQXw=
 local_dir: dist
 file: ".travis.yml"
 on:
    repo: lahirusudesh/my-portfolio-front-end
    branch: master